06-Forms-and-Controllers-HTTP-GET/student-pair/dotnet/SSGeek.Web/Controllers/CalculatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SSGeek.Web.Models;

namespace SSGeek.Web.Controllers
{
    public class CalculatorsController : Controller
    {
        // INSTRUCTIONS
        // As a part of each exercise you will need to 
        // - develop a view for AlienAge, AlienWeight, and AlienTravel that displays a form to submit data
        // - create a new action to process the form submission (e.g. AlienAgeResult, AlienWeightResult, etc.)
        // - create a view that displays the submitted form result

        
        // GET: Calculators/AlienWeight
        public ActionResult AlienWeight()
        {
            return View();
        }

        // GET: calcualtors/alienweightresult?planet=xyz&weight=123
        public ActionResult AlienWeightResult(AlienWeightModel model)
        {
            return View(model);
        }

        // GET: Calculators/AlienAge
        public ActionResult AlienAge()
        {
            return View();
        }

        // GET: calcualtors/alienageresult?planet=xyz&age=123
        public ActionResult AlienAgeResult(AlienAgeModel model)
        {
            return View(model);
        }

        // GET: Calculators/AlienTravel
        public ActionResult AlienTravel()
        {
            return View();
        }

        // GET: calcualtors/alientravelresult?planet=xyz&mode&age=123
        public ActionResult AlienTravelResult(AlienTravelModel model)
        {
            return View(model);
        }



        private List<SelectListItem> planets = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Mercury", Value= "0.38" },
            new SelectListItem() { Text = "Venus", Value= "0.91" },
            new SelectListItem() { Text = "Mars", Value= "0.38"  },
            new SelectListItem() { Text = "Jupiter", Value= "2.34"  },
            new SelectListItem() { Text = "Saturn", Value= "0.93"  },
            new SelectListItem() { Text = "Neptune", Value= "1.12"  },
            new SelectListItem() { Text = "Uranus", Value= "0.92"  }
        };

        private List<SelectListItem> transportationModes = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Walking", Value="walking" },
            new SelectListItem() { Text = "Car", Value = "car" },
            new SelectListItem() { Text = "Bullet Train", Value = "bullet train" },
            new SelectListItem() { Text = "Boeing 747", Value = "boeing 747" },
            new SelectListItem() { Text = "Concorde", Value = "concorde" }
        };
    }
}

06-Forms-and-Controllers-HTTP-GET/student-pair/dotnet/SSGeek.Web/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SSGeek.Web.DAL;
using SSGeek.Web.Models;
using SessionControllerData;

namespace SSGeek.Web.Controllers
{
    public class StoreController : SessionController
    {
        /* Steps
           1. (StoreController)    Create Index Action for store/index
           2. (Index View)         Create Index View for store/index
           TEST
           3. (Global.asax)        Configure DI container to inject IProductDAL > FakeProductDAL
           4. (StoreController)    Enable constructor injection for IProductDAL
           5. (StoreController)    Update Index Action to pass products
           6. (Index View)         Display Products
           TEST
           7. (Index View)         Add Form Tag w/ AddToCart button > POST to store/index
                                   Pass Product Id in Form
           8. (StoreController)    Create POST Index Action for store/index, accept product id & 
                                   redirect to store/viewcart            
           9. (StoreController)    Create ViewCart action for store/viewcart
           10.(ViewCart View)      Display empty View Cart View
           TEST
           11.(StoreController)    POST store/index: retrieve product and add to active
                                   shopping cart
           12.(ShoppingCart)       Create Shopping Cart class to add Product & Quantity
           13.(StoreController)    Guarantee ShoppingCart is in session, create if not
           14.(StoreController)    POST store/index: Update shopping cart with new product
           15.(StoreController)    GET store/viewcart: Retrieve shoping cart from session
           16.(ViewCart View)      Bind go ShoppingCart and disply each product in it
       */

        IProductDAL dal;
        public StoreController(IProductDAL dal)
        {
            this.dal = dal;
        }

        public ActionResult Index()
        {
            var products = dal.GetAllProducts();

            return View(products);
        }

        public ActionResult Detail(int id = 1)
        {
            return View(dal.GetProduct(id));
        }

        [HttpPost]
        public ActionResult AddToCart(int id, int quantity)
        {
            // Add whichever Product productId represents to the shopping cart

            //1.  Get the Product associated with id
            var product = dal.GetProduct(id);

            //2.  Add Product, qty 1 to our active shopping cart
            ShoppingCart cart = GetActiveShoppingCart();
            cart.AddToCart(product, quantity);

            //3. Save shopping cart
            SaveActiveShoppingCart(cart);

            return RedirectToAction("ViewCart");
        }


        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Get the product associated with the id
            var product = dal.GetProduct(id);

            // Find the active shopping cart
            var cart = GetActiveShoppingCart();

            // Remove Qty 1 of product from shopping cart
            cart.RemoveOne(product);

            // Save shopping cart
            SaveActiveShoppingCart(cart);

            // Redirect to ViewCart
            return RedirectToAction("ViewCart");
        }

        public ActionResult ViewCart()
        {
            ShoppingCart cart = GetActiveShoppingCart();
            return View(cart);
        }

        private ShoppingCart GetActiveShoppingCart()
        {
            ShoppingCart cart = null;

            // See if the user has a shopping cart stored in session            
            if (GetSessionData<ShoppingCart>("ShoppingCart") == null)
            {
                cart = new ShoppingCart();
                SaveActiveShoppingCart(cart);                
            }
            else
            {
                cart = GetSessionData<ShoppingCart>("ShoppingCart"); // <-- gets the shopping cart out of session
            }

            // If not, create one for them

            return cart;
        }

        private void SaveActiveShoppingCart(ShoppingCart cart)
        {
            SetSessionData<ShoppingCart>("ShoppingCart", cart);        // <-- saves the shopping cart into session
        }
    }
}

06-Forms-and-Controllers-HTTP-GET/student-pair/dotnet/SSGeek.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SSGeek.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <header>
        <img src="~/images/ssg_logo.png" alt="Solar System Geek logo" />
        <h1>The Solar System</h1>
        <p>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. The vast majority of the system's mass is in the Sun, with most of the remaining mass contained in Jupiter. The four smaller inner planets, Mercury, Venus, Earth and Mars, are terrestrial planets, being primarily composed of rock and metal. The four outer planets are giant planets, being substantially more massive than the terrestrials. The two largest, Jupiter and Saturn, are gas giants, being composed mainly of hydrogen and helium; the two outermost planets, Uranus and Neptune, are ice giants, being composed largely of substances with relatively high melting points compared with hydrogen and helium, called ices, such as water, ammonia and methane. All planets have almost circular orbits that lie within a nearly flat disc called the ecliptic. </p>
    </header>
    <nav>
        <h2>Explore The Solar System</h2>
        <p> Use these state of the art web applications to learn more about the solar system! </p>
        <ul>
            <li><a asp-action="AlienWeight" asp-controller="Calculators">Alien Weight</a></li>
            <li><a asp-action="AlienAge" asp-controller="Calculators">Alien Age</a></li>
            <li><a asp-action="AlienTravel" asp-controller="Calculators">Alien Travel Time</a></li>
            <li><a asp-action="Index" asp-controller="Forum">Space Forum</a></li>
            <li><a asp-action="Index" asp-controller="Store">Space Store</a></li>
        </ul>
    </nav>

    @RenderBody()
    
    <footer>
        <p>&copy; 2018 - SSGeek.Web</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>